providers = ["node"]

[phases.setup]
# Node 22 + npm 10
nixPkgs = ["nodejs_22", "npm-10_x"]

[phases.install]
cmds = ["npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/main.js"
