# .nixpacks.toml
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22"]      # sin npm aquí
nixOverlays = []              # 👈 desactiva el overlay que fuerza npm-9

[phases.install]
cmds = [
  "node -v && npm -v",
  "npm i -g npm@10.8.2",      # 👈 sube a npm 10
  "npm -v",
  "npm ci --include=dev"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/main.js"
