app = "multiPlatformVenue-back"
primary_region = "syd"

[http_service]
  internal_port = 3001            # <-- usa el puerto real d e tu app
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"
